Axstrad\Bundle\PageBundle\Entity\Page:
    type: entity
    table: axstrad_page
    fields:
        active:
            type: boolean
            options:
                default: false
    axstrad:
        activatable:
            field_name: active

