language: php
php:
  - 5.4
env:
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.6.*"
  - SYMFONY_VERSION="2.7.*@dev"
  # - SYMFONY_VERSION="3.0.*@dev"
before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist
script:
  - php ./vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="80b65a15a783f3ca91af2635f701052e94179ebf84aad0a031dcc90dddd30394" --format=php-clover coverage.clover
matrix:
  allow_failures:
    - env: SYMFONY_VERSION="2.7.*@dev"

  fast_finish: true

notifications:
  email:
    - dev@dankempster.co.uk

branches:
  only:
    - develop
    - master
